name:         My Comics!
markdown:     redcarpet
pygments:     true
source:       source
destination:  public
author:       tamouse
paginate:     50
paginate_path: "comics/page:num"
posts:        "_posts"
download_path: images
